# 한국 거래소에서 시가총액 데이터 수집
* KRX에서 상장 기업의 시가총액 데이터를 기간별로 수집하는 방법에 대해서 알아보겠습니다. 
* selenium, BeautifulSoup, requests, json 라이브러리를 사용하여 진행하겠습니다.

In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import requests
import json
import time

* Chrome를 실제로 운전하게 될 driver라는 웹 드라이버 객체를 생성합니다. 
    > Chrome, Firefox, PhantomJS등 각각의 브라우저마다 드라이버가 다르고, 호출 함수도 다릅니다. 
* 드라이버에게 파이썬 코드로 우리가 웹에서 하는 행동을 지시할 수 있습니다. 
* chromedriver.exe 파일이 저장되어 있는 경로를 Chrome() 메소드에 전달

In [2]:
driver = webdriver.Chrome("C:\chromedriver\chromedriver.exe")

* get() 메소드를 사용하여 사용자가 원하는 주소로 이동합니다.
* 이동 뒤에 sleep() 함수를 사용하여 페이지가 완전히 로딩될 때까지 기다립니다.

In [3]:
# 종합 시황 다운로드 받기 
driver.get('http://marketdata.krx.co.kr/mdi#document=0101')
# 5초간 기다림
time.sleep(5)

* find_element_by_css_selector 메소드는 selector에서 복사한 값을 기준으로 해당 지정한 곳의 정보를 찾습니다.
* 찾고 난 뒤에 텍스트 상자라면 clear()를 사용하여 값을 삭제할수도, 버튼이라면 click()를 사용하여 실제 클릭을 진행할 수 있습니다.
* 아래 예제는 문서 3개를 다운로드를 자동으로 받는 예제입니다. click() 함수를 사용하여 자동으로 다운로드 합니다.

In [4]:
driver.find_element_by_css_selector("#c9f0f895fb98ab9159f51fd0297e236d > div.coreboard-data.design-board-normal > table > tbody > tr:nth-child(1) > td.attach-td").click()
driver.find_element_by_css_selector("#c9f0f895fb98ab9159f51fd0297e236d > div.coreboard-data.design-board-normal > table > tbody > tr:nth-child(1) > td.attach-td > div > div > ul > li > a").click()

In [5]:
driver.find_element_by_css_selector("#c9f0f895fb98ab9159f51fd0297e236d > div.coreboard-data.design-board-normal > table > tbody > tr:nth-child(2) > td.attach-td > div > button").click()           
driver.find_element_by_css_selector("#c9f0f895fb98ab9159f51fd0297e236d > div.coreboard-data.design-board-normal > table > tbody > tr:nth-child(2) > td.attach-td > div > div > ul > li > a").click()

In [6]:
driver.find_element_by_css_selector("#c9f0f895fb98ab9159f51fd0297e236d > div.coreboard-data.design-board-normal > table > tbody > tr:nth-child(3) > td.attach-td > div > button").click()           
driver.find_element_by_css_selector("#c9f0f895fb98ab9159f51fd0297e236d > div.coreboard-data.design-board-normal > table > tbody > tr:nth-child(3) > td.attach-td > div > div > ul > li > a").click()

* 조회 기간의 글자를 clear() 메소드를 사용하여 깨끗하기 지웁니다. 
* 그리고 send_keys() 메소드를 사용하여 내가 원하는 날짜 값을 전달합니다.

In [7]:
driver.find_element_by_css_selector('#fromdate1679091c5a880faf6fb5e6087eb1b2dc').clear()

In [8]:
driver.find_element_by_css_selector('#fromdate1679091c5a880faf6fb5e6087eb1b2dc').send_keys('20190628')

* 자동화를 진행하게 된다면 20190628처럼 사람이 직접 입력하지 않고 자동으로 만들어야 합니다. 
* 우리가 이전 시간에 배웠던 datetime 라이브러리의 date 클래스의 today() 메소드를 사용하여 현재 날짜를 자동으로 가져옵니다.

In [9]:
import datetime

In [10]:
datetime.date.today()

datetime.date(2019, 7, 2)

* str() 함수를 사용하면 문자열로 변경할 수 있고, 문자열 메소드인 replace()를 사용하면 -를 제거할 수 있습니다.

In [11]:
str(datetime.date.today()).replace("-", "")

'20190702'

* date객체에서 strftime() 메소드를 사용하면 문자열 변환을 포맷에 맞게 출력할 수 있습니다.

In [12]:
today = datetime.date.today()

* %Y : year
* %m : Month
* %d : day

In [13]:
today.strftime("%Y%m%d")

'20190702'

# 시가총액 데이터 다운로드 받기

* 시가 총액을 다운로드 받을 수 있는 사이트로 이동합니다.
* refresh() 함수는 페이지를 새로고침 합니다.

In [14]:
driver.get('http://marketdata.krx.co.kr/mdi#document=040402')
driver.refresh()
# 5초간 페이지에서 기다립니다. 
time.sleep(5)

* code 값은 매번 값이 변경되고 지금 code값을 설정하여도 다시 실행하면 동작하지 않은 것을 확인할 수 있습니다.
* form 태그의 data-code 값은 웹 페이지에 접속하고 자바스크립트가 실행되어야 최종적으로 알 수 있는 데이터이기 때문에 selenium를 사용합니다.
* form 태그의 action 값과 method값으로 해당 값을 찾고 'data-code'의 값을 추출합니다.
* payload라는 dict는 post 방식으로 krx하고 통신을 하기 위한 요청사항 정보입니다. 이 정보를 바탕으로 서버에서 정보를 전달합니다.
* 이때 웹 페이지에 있는 data-code 값을 확인하여 정상적인 data-code면 제대로 된 값을 전달합니다.

In [15]:
bs = BeautifulSoup(driver.page_source, "html.parser") 
rt2 = bs.find("form", {"action" : "/contents/MKD/99/MKD99000001.jspx", 
                       "method" : "post", "data-bld":"MKD/04/0404/04040200/mkd04040200_01"})


payload = {'market_gubun' : 'ALL',
           'sect_tp_cd' : 'ALL',
           'schdate' : '20190627',
           'pagePath' : '/contents/MKD/04/0404/04040200/MKD04040200.jsp'
           }

payload['code'] = rt2['data-code']

* curPage는 시가총액의 페이지 번호를 의미합니다. 아래 예제는 1 페이지를 설정합니다.

In [16]:
payload['curPage'] = 1

In [17]:
ret= requests.post("http://marketdata.krx.co.kr/contents/MKD/99/MKD99000001.jspx",  data=payload)

In [18]:
ret.text

'{"시가총액 상하위":[{"rn":"1","isu_cd":"005930","kor_shrt_isu_nm":"삼성전자","isu_cur_pr":"46,500","fluc_tp_cd":"1","prv_dd_cmpr":"800","updn_rate":"1.8","isu_tr_vl":"12,603,534","isu_tr_amt":"583,888,994,023","opnprc":"46,000","hgprc":"46,600","lwprc":"45,750","cur_pr_tot_amt":"277,594,888,575,000","tot_amt_per":"16.65","lst_stk_vl":"5,969,782,550","f1":"3,411,981,118","f2":"57.15","totCnt":"2398"},{"rn":"2","isu_cd":"000660","kor_shrt_isu_nm":"SK하이닉스","isu_cur_pr":"70,200","fluc_tp_cd":"1","prv_dd_cmpr":"1,300","updn_rate":"1.9","isu_tr_vl":"5,361,201","isu_tr_amt":"378,736,507,000","opnprc":"70,100","hgprc":"71,600","lwprc":"69,700","cur_pr_tot_amt":"51,105,766,023,000","tot_amt_per":"3.07","lst_stk_vl":"728,002,365","f1":"367,493,736","f2":"50.48","totCnt":""},{"rn":"3","isu_cd":"005935","kor_shrt_isu_nm":"삼성전자우","isu_cur_pr":"38,000","fluc_tp_cd":"1","prv_dd_cmpr":"100","updn_rate":"0.3","isu_tr_vl":"1,399,856","isu_tr_amt":"53,134,817,735","opnprc":"37,600","hgprc":"38,150","lwprc":"37,600","cur_pr_tot_amt":"31,269,694,600,000","tot_amt_per":"1.88","lst_stk_vl":"822,886,700","f1":"762,330,049","f2":"92.64","totCnt":""},{"rn":"4","isu_cd":"005380","kor_shrt_isu_nm":"현대차","isu_cur_pr":"140,500","fluc_tp_cd":"2","prv_dd_cmpr":"1,000","updn_rate":"-0.7","isu_tr_vl":"343,337","isu_tr_amt":"48,441,831,000","opnprc":"141,000","hgprc":"142,500","lwprc":"139,500","cur_pr_tot_amt":"30,020,380,273,500","tot_amt_per":"1.80","lst_stk_vl":"213,668,187","f1":"94,615,472","f2":"44.28","totCnt":""},{"rn":"5","isu_cd":"068270","kor_shrt_isu_nm":"셀트리온","isu_cur_pr":"204,000","fluc_tp_cd":"2","prv_dd_cmpr":"6,500","updn_rate":"-3.1","isu_tr_vl":"609,613","isu_tr_amt":"125,509,765,000","opnprc":"207,500","hgprc":"209,000","lwprc":"203,000","cur_pr_tot_amt":"26,179,130,280,000","tot_amt_per":"1.57","lst_stk_vl":"128,329,070","f1":"27,239,509","f2":"21.23","totCnt":""},{"rn":"6","isu_cd":"051910","kor_shrt_isu_nm":"LG화학","isu_cur_pr":"349,500","fluc_tp_cd":"1","prv_dd_cmpr":"2,000","updn_rate":"0.6","isu_tr_vl":"172,767","isu_tr_amt":"59,918,992,000","opnprc":"346,000","hgprc":"350,000","lwprc":"343,000","cur_pr_tot_amt":"24,672,023,878,500","tot_amt_per":"1.48","lst_stk_vl":"70,592,343","f1":"27,397,742","f2":"38.81","totCnt":""},{"rn":"7","isu_cd":"012330","kor_shrt_isu_nm":"현대모비스","isu_cur_pr":"235,500","fluc_tp_cd":"1","prv_dd_cmpr":"2,500","updn_rate":"1.1","isu_tr_vl":"206,434","isu_tr_amt":"48,290,490,000","opnprc":"229,000","hgprc":"236,000","lwprc":"228,000","cur_pr_tot_amt":"22,444,726,437,000","tot_amt_per":"1.35","lst_stk_vl":"95,306,694","f1":"45,640,625","f2":"47.89","totCnt":""},{"rn":"8","isu_cd":"055550","kor_shrt_isu_nm":"신한지주","isu_cur_pr":"45,150","fluc_tp_cd":"1","prv_dd_cmpr":"550","updn_rate":"1.2","isu_tr_vl":"1,011,900","isu_tr_amt":"45,363,365,050","opnprc":"44,200","hgprc":"45,200","lwprc":"44,150","cur_pr_tot_amt":"21,410,111,353,050","tot_amt_per":"1.28","lst_stk_vl":"474,199,587","f1":"319,203,336","f2":"67.31","totCnt":""},{"rn":"9","isu_cd":"005490","kor_shrt_isu_nm":"POSCO","isu_cur_pr":"244,500","fluc_tp_cd":"1","prv_dd_cmpr":"1,500","updn_rate":"0.6","isu_tr_vl":"174,978","isu_tr_amt":"42,601,962,500","opnprc":"242,500","hgprc":"245,500","lwprc":"240,500","cur_pr_tot_amt":"21,317,181,157,500","tot_amt_per":"1.28","lst_stk_vl":"87,186,835","f1":"47,158,312","f2":"54.09","totCnt":""},{"rn":"10","isu_cd":"207940","kor_shrt_isu_nm":"삼성바이오로직스","isu_cur_pr":"315,000","fluc_tp_cd":"1","prv_dd_cmpr":"1,500","updn_rate":"0.5","isu_tr_vl":"56,497","isu_tr_amt":"17,875,057,500","opnprc":"313,500","hgprc":"319,000","lwprc":"312,000","cur_pr_tot_amt":"20,841,975,000,000","tot_amt_per":"1.25","lst_stk_vl":"66,165,000","f1":"5,745,073","f2":"8.68","totCnt":""}]}'

* 시가총액 데이터를 selenium를 사용하여 데이터를 수집하면 자바스크립트가 실행되고, 이미지가 실행되는 등 속도가 많이 느립니다. 
* 그래서 requests의 post 방식은 값을 빠르게 전달받기 위해서 사용합니다. 
* 아래 for문을 300번까지 돌린 이유는 데이터가 없다면 크기를 확인하고(100) 이하면 종료 로직이 들어 있기 때문에 크게 잡았습니다.
* 종목은 수시로 변경될 수 있기 때문에 숫자를 딱 정하는 것보다 약간 더 크게 만들어 로직을 넣는 것을 추천합니다.

In [20]:
rt_list = []
for cnt in range(1,300):
    if(cnt % 10 == 0):
        print (cnt)
    payload['curPage'] = cnt
    rt3 = requests.post("http://marketdata.krx.co.kr/contents/MKD/99/MKD99000001.jspx",  data=payload)
    if(len(rt3.text) > 100):
        rt_list.append(rt3.text)
    else:
        break

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240

* rt_list의 원소 하나하나는 문자열로 이루어져 있습니다. 눈으로 확인하면 dict 형태이지만(서버에선 json형식으로 전달) 문자열이 때문에 json 라이브러리의 힘을 빌려야 합니다.

In [21]:
type(rt_list[0])

str

* json의 loads() 함수를 사용하여 문자열을 dict 형태로 변환합니다. 그리고 '시가총액 상하위' 키를 가지고 있는 값을 추출하여 DataFrame을 생성합니다.

In [22]:
pd.DataFrame(json.loads(rt_list[0])['시가총액 상하위'])

,cur_pr_tot_amt,f1,f2,fluc_tp_cd,hgprc,isu_cd,isu_cur_pr,isu_tr_amt,isu_tr_vl,kor_shrt_isu_nm,lst_stk_vl,lwprc,opnprc,prv_dd_cmpr,rn,totCnt,tot_amt_per,updn_rate
0,"277,594,888,575,000","3,411,981,118",57.15,1,"46,600",005930,"46,500","583,888,994,023","12,603,534",삼성전자,"5,969,782,550","45,750","46,000",800,1,2398,16.65,1.8
1,"51,105,766,023,000","367,493,736",50.48,1,"71,600",000660,"70,200","378,736,507,000","5,361,201",SK하이닉스,"728,002,365","69,700","70,100","1,300",2,,3.07,1.9
2,"31,269,694,600,000","762,330,049",92.64,1,"38,150",005935,"38,000","53,134,817,735","1,399,856",삼성전자우,"822,886,700","37,600","37,600",100,3,,1.88,0.3
3,"30,020,380,273,500","94,615,472",44.28,2,"142,500",005380,"140,500","48,441,831,000","343,337",현대차,"213,668,187","139,500","141,000","1,000",4,,1.80,-0.7
4,"26,179,130,280,000","27,239,509",21.23,2,"209,000",068270,"204,000","125,509,765,000","609,613",셀트리온,"128,329,070","203,000","207,500","6,500",5,,1.57,-3.1
5,"24,672,023,878,500","27,397,742",38.81,1,"350,000",051910,"349,500","59,918,992,000","172,767",LG화학,"70,592,343","343,000","346,000","2,000",6,,1.48,0.6
6,"22,444,726,437,000","45,640,625",47.89,1,"236,000",012330,"235,500","48,290,490,000","206,434",현대모비스,"95,306,694","228,000","229,000","2,500",7,,1.35,1.1
7,"21,410,111,353,050","319,203,336",67.31,1,"45,200",055550,"45,150","45,363,365,050","1,011,900",신한지주,"474,199,587","44,150","44,200",550,8,,1.28,1.2
8,"21,317,181,157,500","47,158,312",54.09,1,"245,500",005490,"244,500","42,601,962,500","174,978",POSCO,"87,186,835","240,500","242,500","1,500",9,,1.28,0.6
9,"20,841,975,000,000","5,745,073",8.68,1,"319,000",207940,"315,000","17,875,057,500","56,497",삼성바이오로직스,"66,165,000","312,000","313,500","1,500",10,,1.25,0.5

* 이 작업을 for문을 돌려서 concat() 함수(DataFrame을 row단위로 합쳐주는 역할) 호출하여 DataFrame을 total_df라는 하나의 데이터 합칩니다.

In [23]:
total_df = pd.DataFrame()
for x in rt_list:
    rt = json.loads(x)
    total_df = pd.concat([total_df, pd.DataFrame(rt['시가총액 상하위'])])

In [24]:
total_df

,cur_pr_tot_amt,f1,f2,fluc_tp_cd,hgprc,isu_cd,isu_cur_pr,isu_tr_amt,isu_tr_vl,kor_shrt_isu_nm,lst_stk_vl,lwprc,opnprc,prv_dd_cmpr,rn,totCnt,tot_amt_per,updn_rate
0,"277,594,888,575,000","3,411,981,118",57.15,1,"46,600",005930,"46,500","583,888,994,023","12,603,534",삼성전자,"5,969,782,550","45,750","46,000",800,1,2398,16.65,1.8
1,"51,105,766,023,000","367,493,736",50.48,1,"71,600",000660,"70,200","378,736,507,000","5,361,201",SK하이닉스,"728,002,365","69,700","70,100","1,300",2,,3.07,1.9
2,"31,269,694,600,000","762,330,049",92.64,1,"38,150",005935,"38,000","53,134,817,735","1,399,856",삼성전자우,"822,886,700","37,600","37,600",100,3,,1.88,0.3
3,"30,020,380,273,500","94,615,472",44.28,2,"142,500",005380,"140,500","48,441,831,000","343,337",현대차,"213,668,187","139,500","141,000","1,000",4,,1.80,-0.7
4,"26,179,130,280,000","27,239,509",21.23,2,"209,000",068270,"204,000","125,509,765,000","609,613",셀트리온,"128,329,070","203,000","207,500","6,500",5,,1.57,-3.1
5,"24,672,023,878,500","27,397,742",38.81,1,"350,000",051910,"349,500","59,918,992,000","172,767",LG화학,"70,592,343","343,000","346,000","2,000",6,,1.48,0.6
6,"22,444,726,437,000","45,640,625",47.89,1,"236,000",012330,"235,500","48,290,490,000","206,434",현대모비스,"95,306,694","228,000","229,000","2,500",7,,1.35,1.1
7,"21,410,111,353,050","319,203,336",67.31,1,"45,200",055550,"45,150","45,363,365,050","1,011,900",신한지주,"474,199,587","44,150","44,200",550,8,,1.28,1.2
8,"21,317,181,157,500","47,158,312",54.09,1,"245,500",005490,"244,500","42,601,962,500","174,978",POSCO,"87,186,835","240,500","242,500","1,500",9,,1.28,0.6
9,"20,841,975,000,000","5,745,073",8.68,1,"319,000",207940,"315,000","17,875,057,500","56,497",삼성바이오로직스,"66,165,000","312,000","313,500","1,500",10,,1.25,0.5
0,"20,792,020,582,500","32,656,923",40.44,2,"260,000",017670,"257,500","36,981,155,500","143,357",SK텔레콤,"80,745,711","256,000","259,000","1,500",11,2398,1.25,-0.6
1,"20,600,401,843,000","7,058,412",45.19,1,"1,324,000",051900,"1,319,000","25,286,975,118","19,236",LG생활건강,"15,618,197","1,295,000","1,304,000","16,000",12,,1.24,1.2
2,"19,128,602,817,750","282,948,004",67.67,1,"45,900",105560,"45,750","39,925,719,450","877,190",KB금융,"418,111,537","44,900","45,050",350,13,,1.15,0.8
3,"18,953,540,425,000","95,755,541",58.10,2,"116,000",035420,"115,000","43,045,588,500","375,582",NAVER,"164,813,395","113,000","115,500",500,14,,1.14,-0.4
4,"18,286,120,145,200","26,549,336",14.00,1,"97,000",028260,"96,400","21,564,022,000","224,316",삼성물산,"189,690,043","94,800","95,800",500,15,,1.10,0.5
5,"17,775,182,765,950","174,395,984",43.02,1,"44,050",000270,"43,850","44,278,501,900","1,008,008",기아차,"405,363,347","43,350","43,850",200,16,,1.07,0.5
6,"16,800,000,000,000","33,334,709",16.67,1,"84,400",032830,"84,000","12,456,100,800","148,773",삼성생명,"200,000,000","82,600","83,100",400,17,,1.01,0.5
7,"16,713,604,800,000","10,267,362",13.27,1,"218,000",018260,"216,000","16,975,962,000","78,453",삼성에스디에스,"77,377,800","213,500","215,500",500,18,,1.00,0.2
8,"16,466,378,575,050","170,848,986",26.61,2,"25,900",015760,"25,650","22,527,547,150","876,350",한국전력,"641,964,077","25,600","25,700",150,19,,0.99,-0.6
9,"16,464,309,498,000","19,447,838",27.64,2,"235,500",034730,"234,000","20,353,354,000","87,126",SK,"70,360,297","232,000","234,000","1,000",20,,0.99,-0.4
0,"16,331,575,875,000","29,671,405",43.15,1,"238,000",006400,"237,500","69,777,052,500","296,054",삼성SDI,"68,764,530","229,000","230,000","8,500",21,2398,0.98,3.7
1,"14,840,723,022,000","34,442,820",37.25,3,"161,500",096770,"160,500","28,779,828,000","179,252",SK이노베이션,"92,465,564","159,000","160,000",0,22,,0.89,0.0
2,"13,578,227,953,300","70,290,156",51.20,2,"99,300",033780,"98,900","26,608,874,300","268,815",KT&G,"137,292,497","98,600","99,000",300,23,,0.81,-0.3
3,"13,338,666,226,300","60,285,763",34.94,1,"77,700",003550,"77,300","15,560,863,900","201,788",LG,"172,557,131","76,000","76,600",300,24,,0.80,0.4
4,"13,042,730,775,800","55,675,321",34.02,1,"80,400",066570,"79,700","39,427,381,100","494,293",LG전자,"163,647,814","79,100","79,500",400,25,,0.78,0.5
5,"12,814,893,408,500","23,930,790",50.51,3,"271,000",000810,"270,500","18,594,496,000","68,876",삼성화재,"47,374,837","268,000","269,000",0,26,,0.77,0.0
6,"11,229,053,118,800","211,956,550",70.60,2,"37,500",086790,"37,400","31,421,661,450","842,062",하나금융지주,"300,242,062","37,000","37,050",100,27,,0.67,-0.3
7,"10,972,672,049,500","20,783,932",24.91,1,"133,500",035720,"131,500","92,792,636,000","704,159",카카오,"83,442,373","130,000","131,000","2,000",28,,0.66,1.5
8,"10,556,277,082,000","10,935,211",49.83,1,"482,500",036570,"481,000","26,689,255,000","55,773",엔씨소프트,"21,946,522","470,000","475,500","5,500",29,,0.63,1.2
9,"10,497,450,810,000","21,019,452",24.53,1,"126,000",251270,"122,500","61,198,869,500","498,944",넷마블,"85,693,476","119,000","124,000","1,000",30,,0.63,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,"5,139,521,920","1,741",0.28,2,"8,340",001525,"8,320","51,895,160","6,280",동양우,"617,731","8,250","8,280",70,2369,,0.00,-0.8
9,"5,083,048,750","4,981",1.59,2,"16,350",003075,"16,250","4,382,450",271,코오롱글로벌우,"312,803","16,100","16,250",150,2370,,0.00,-0.9
0,"4,950,000,000",0,0.00,0,0,271780,"1,650",0,0,비엔에프코퍼레이션,"3,000,000",0,0,0,2371,2398,0.00,0.0
1,"4,734,119,400","5,137",4.57,1,"43,000",000995,"42,150","61,931,600","1,476",DB하이텍1우,"112,316","41,000","41,000","1,150",2372,,0.00,2.8
2,"4,693,975,700","31,546",6.70,1,"9,980",000145,"9,970","9,250,210",932,하이트진로홀딩스우,"470,810","9,830","9,830",10,2373,,0.00,0.1
3,"4,525,302,800","7,103",2.41,1,"17,650",002787,"15,350","3,598,488,000","217,986",진흥기업2우B,"294,808","14,800","14,800",600,2374,,0.00,4.1
4,"4,523,520,000","9,332",1.22,1,"5,940",000545,"5,890","10,195,330","1,744",흥국화재우,"768,000","5,770","5,840",40,2375,,0.00,0.7
5,"4,515,000,000","3,454",0.66,1,"8,610",001755,"8,600","737,110",87,한양증권우,"525,000","8,400","8,400",200,2376,,0.00,2.4
6,"4,494,018,750","2,012",1.20,2,"26,900",001065,"26,850","21,882,300",819,JW중외제약우,"167,375","26,550","26,700",50,2377,,0.00,-0.2
7,"4,440,278,682",0,0.00,1,609,092590,609,609,1,럭스피아,"7,291,098",609,609,16,2378,,0.00,2.7
8,"4,142,182,200","43,100",19.09,1,"18,900",005965,"18,350","98,388,150","5,334",동부건설우,"225,732","17,950","18,200",150,2379,,0.00,0.8
9,"4,104,000,000",0,0.00,1,"1,520",224020,"1,520","1,520",1,에스케이씨에스,"2,700,000","1,520","1,520",75,2380,,0.00,5.2
0,"3,810,086,000","1,008",1.15,1,"43,500",001067,"43,400","6,528,950",152,JW중외제약2우B,"87,790","42,700","43,000",400,2381,2398,0.00,0.9
1,"3,767,251,380",0,0.00,2,360,217910,290,650,2,에스제이켐,"12,990,522",290,360,49,2382,,0.00,-14.4
2,"3,667,950,000","1,862",1.01,1,"19,800",000325,"19,800","22,328,950","1,148",노루홀딩스우,"185,250","19,300","19,600",200,2383,,0.00,1.0
3,"3,611,513,935",0,0.00,2,"1,395",084440,"1,205","2,600",2,유비온,"2,997,107","1,205","1,395",75,2384,,0.00,-5.9
4,"3,597,178,410","1,010",0.13,1,"4,590",00781K,"4,590","2,203,165",494,코리아써키트2우B,"783,699","4,315","4,315",130,2385,,0.00,2.9
5,"3,583,476,000",0,0.00,1,"1,800",208890,"1,800","1,800",1,에듀파트너,"1,990,820","1,800","1,800",180,2386,,0.00,11.1
6,"3,540,480,000",452,0.29,1,"23,300",000547,"23,050","23,699,100","1,029",흥국화재2우B,"153,600","22,900","23,250",50,2387,,0.00,0.2
7,"3,540,236,400",0,0.00,2,"9,060",270210,"7,650","913,650",101,에스알바이오텍,"462,776","7,650","9,060","1,270",2388,,0.00,-14.2
8,"3,442,853,700",240,0.17,2,"25,150",032685,"24,100","41,026,800","1,696",소프트센우,"142,857","23,700","24,750",650,2389,,0.00,-2.6
9,"3,279,863,395","198,102",0.94,0,0,149940,155,0,0,모다,"21,160,409",0,0,0,2390,,0.00,0.0
0,"3,270,831,400",0,0.00,2,"10,650",001527,"10,600","812,700",77,동양2우B,"308,569","10,500","10,550",150,2391,2398,0.00,-1.4
1,"3,142,132,000","2,669",1.63,1,"19,400",000227,"19,150","9,651,650",507,유유제약2우B,"164,080","18,900","19,000",150,2392,,0.00,0.8
2,"3,072,847,200",0,0.00,1,"24,000",001799,"23,700","39,700,950","1,684",대한제당3우B,"129,656","23,400","23,500",150,2393,,0.00,0.6
3,"2,959,295,040",0,0.00,2,390,227420,390,"4,704,826","13,571",포레스팅블록체인,"7,587,936",341,350,10,2394,,0.00,-2.5
4,"2,761,538,816","7,990",0.07,0,0,223220,256,0,0,아이피몬스터,"10,787,261",0,0,0,2395,,0.00,0.0
5,"2,732,034,900",200,0.22,2,"31,300",001529,"30,450","32,677,500","1,066",동양3우B,"89,722","30,350","30,350",50,2396,,0.00,-0.2
6,"2,692,007,120",0,0.00,0,0,247300,440,0,0,인프라웨어테크놀러지,"6,118,198",0,0,0,2397,,0.00,0.0
7,"1,057,615,548",0,0.00,5,198,135270,148,"8,030,743","52,620",세종머티리얼즈,"7,146,051",148,185,25,2398,,0.00,-14.4

* 해당 데이터는 날짜 데이터가 없기 때문에 post()안에 요청했던 날짜로 date라는 컬럼을 생성하고 날짜를 넣어줍니다. 
* 이 작업도 자동화로 해야겠죠? 위의 코드를 바탕으로 만들어보는 것을 권장합니다.

In [25]:
total_df['date']= '2019-06-27'

* 인덱스 값을 초기화합니다.

In [26]:
total_df.reset_index(drop=True)

,cur_pr_tot_amt,f1,f2,fluc_tp_cd,hgprc,isu_cd,isu_cur_pr,isu_tr_amt,isu_tr_vl,kor_shrt_isu_nm,lst_stk_vl,lwprc,opnprc,prv_dd_cmpr,rn,totCnt,tot_amt_per,updn_rate,date
0,"277,594,888,575,000","3,411,981,118",57.15,1,"46,600",005930,"46,500","583,888,994,023","12,603,534",삼성전자,"5,969,782,550","45,750","46,000",800,1,2398,16.65,1.8,2019-06-27
1,"51,105,766,023,000","367,493,736",50.48,1,"71,600",000660,"70,200","378,736,507,000","5,361,201",SK하이닉스,"728,002,365","69,700","70,100","1,300",2,,3.07,1.9,2019-06-27
2,"31,269,694,600,000","762,330,049",92.64,1,"38,150",005935,"38,000","53,134,817,735","1,399,856",삼성전자우,"822,886,700","37,600","37,600",100,3,,1.88,0.3,2019-06-27
3,"30,020,380,273,500","94,615,472",44.28,2,"142,500",005380,"140,500","48,441,831,000","343,337",현대차,"213,668,187","139,500","141,000","1,000",4,,1.80,-0.7,2019-06-27
4,"26,179,130,280,000","27,239,509",21.23,2,"209,000",068270,"204,000","125,509,765,000","609,613",셀트리온,"128,329,070","203,000","207,500","6,500",5,,1.57,-3.1,2019-06-27
5,"24,672,023,878,500","27,397,742",38.81,1,"350,000",051910,"349,500","59,918,992,000","172,767",LG화학,"70,592,343","343,000","346,000","2,000",6,,1.48,0.6,2019-06-27
6,"22,444,726,437,000","45,640,625",47.89,1,"236,000",012330,"235,500","48,290,490,000","206,434",현대모비스,"95,306,694","228,000","229,000","2,500",7,,1.35,1.1,2019-06-27
7,"21,410,111,353,050","319,203,336",67.31,1,"45,200",055550,"45,150","45,363,365,050","1,011,900",신한지주,"474,199,587","44,150","44,200",550,8,,1.28,1.2,2019-06-27
8,"21,317,181,157,500","47,158,312",54.09,1,"245,500",005490,"244,500","42,601,962,500","174,978",POSCO,"87,186,835","240,500","242,500","1,500",9,,1.28,0.6,2019-06-27
9,"20,841,975,000,000","5,745,073",8.68,1,"319,000",207940,"315,000","17,875,057,500","56,497",삼성바이오로직스,"66,165,000","312,000","313,500","1,500",10,,1.25,0.5,2019-06-27
10,"20,792,020,582,500","32,656,923",40.44,2,"260,000",017670,"257,500","36,981,155,500","143,357",SK텔레콤,"80,745,711","256,000","259,000","1,500",11,2398,1.25,-0.6,2019-06-27
11,"20,600,401,843,000","7,058,412",45.19,1,"1,324,000",051900,"1,319,000","25,286,975,118","19,236",LG생활건강,"15,618,197","1,295,000","1,304,000","16,000",12,,1.24,1.2,2019-06-27
12,"19,128,602,817,750","282,948,004",67.67,1,"45,900",105560,"45,750","39,925,719,450","877,190",KB금융,"418,111,537","44,900","45,050",350,13,,1.15,0.8,2019-06-27
13,"18,953,540,425,000","95,755,541",58.10,2,"116,000",035420,"115,000","43,045,588,500","375,582",NAVER,"164,813,395","113,000","115,500",500,14,,1.14,-0.4,2019-06-27
14,"18,286,120,145,200","26,549,336",14.00,1,"97,000",028260,"96,400","21,564,022,000","224,316",삼성물산,"189,690,043","94,800","95,800",500,15,,1.10,0.5,2019-06-27
15,"17,775,182,765,950","174,395,984",43.02,1,"44,050",000270,"43,850","44,278,501,900","1,008,008",기아차,"405,363,347","43,350","43,850",200,16,,1.07,0.5,2019-06-27
16,"16,800,000,000,000","33,334,709",16.67,1,"84,400",032830,"84,000","12,456,100,800","148,773",삼성생명,"200,000,000","82,600","83,100",400,17,,1.01,0.5,2019-06-27
17,"16,713,604,800,000","10,267,362",13.27,1,"218,000",018260,"216,000","16,975,962,000","78,453",삼성에스디에스,"77,377,800","213,500","215,500",500,18,,1.00,0.2,2019-06-27
18,"16,466,378,575,050","170,848,986",26.61,2,"25,900",015760,"25,650","22,527,547,150","876,350",한국전력,"641,964,077","25,600","25,700",150,19,,0.99,-0.6,2019-06-27
19,"16,464,309,498,000","19,447,838",27.64,2,"235,500",034730,"234,000","20,353,354,000","87,126",SK,"70,360,297","232,000","234,000","1,000",20,,0.99,-0.4,2019-06-27
20,"16,331,575,875,000","29,671,405",43.15,1,"238,000",006400,"237,500","69,777,052,500","296,054",삼성SDI,"68,764,530","229,000","230,000","8,500",21,2398,0.98,3.7,2019-06-27
21,"14,840,723,022,000","34,442,820",37.25,3,"161,500",096770,"160,500","28,779,828,000","179,252",SK이노베이션,"92,465,564","159,000","160,000",0,22,,0.89,0.0,2019-06-27
22,"13,578,227,953,300","70,290,156",51.20,2,"99,300",033780,"98,900","26,608,874,300","268,815",KT&G,"137,292,497","98,600","99,000",300,23,,0.81,-0.3,2019-06-27
23,"13,338,666,226,300","60,285,763",34.94,1,"77,700",003550,"77,300","15,560,863,900","201,788",LG,"172,557,131","76,000","76,600",300,24,,0.80,0.4,2019-06-27
24,"13,042,730,775,800","55,675,321",34.02,1,"80,400",066570,"79,700","39,427,381,100","494,293",LG전자,"163,647,814","79,100","79,500",400,25,,0.78,0.5,2019-06-27
25,"12,814,893,408,500","23,930,790",50.51,3,"271,000",000810,"270,500","18,594,496,000","68,876",삼성화재,"47,374,837","268,000","269,000",0,26,,0.77,0.0,2019-06-27
26,"11,229,053,118,800","211,956,550",70.60,2,"37,500",086790,"37,400","31,421,661,450","842,062",하나금융지주,"300,242,062","37,000","37,050",100,27,,0.67,-0.3,2019-06-27
27,"10,972,672,049,500","20,783,932",24.91,1,"133,500",035720,"131,500","92,792,636,000","704,159",카카오,"83,442,373","130,000","131,000","2,000",28,,0.66,1.5,2019-06-27
28,"10,556,277,082,000","10,935,211",49.83,1,"482,500",036570,"481,000","26,689,255,000","55,773",엔씨소프트,"21,946,522","470,000","475,500","5,500",29,,0.63,1.2,2019-06-27
29,"10,497,450,810,000","21,019,452",24.53,1,"126,000",251270,"122,500","61,198,869,500","498,944",넷마블,"85,693,476","119,000","124,000","1,000",30,,0.63,0.8,2019-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368,"5,139,521,920","1,741",0.28,2,"8,340",001525,"8,320","51,895,160","6,280",동양우,"617,731","8,250","8,280",70,2369,,0.00,-0.8,2019-06-27
2369,"5,083,048,750","4,981",1.59,2,"16,350",003075,"16,250","4,382,450",271,코오롱글로벌우,"312,803","16,100","16,250",150,2370,,0.00,-0.9,2019-06-27
2370,"4,950,000,000",0,0.00,0,0,271780,"1,650",0,0,비엔에프코퍼레이션,"3,000,000",0,0,0,2371,2398,0.00,0.0,2019-06-27
2371,"4,734,119,400","5,137",4.57,1,"43,000",000995,"42,150","61,931,600","1,476",DB하이텍1우,"112,316","41,000","41,000","1,150",2372,,0.00,2.8,2019-06-27
2372,"4,693,975,700","31,546",6.70,1,"9,980",000145,"9,970","9,250,210",932,하이트진로홀딩스우,"470,810","9,830","9,830",10,2373,,0.00,0.1,2019-06-27
2373,"4,525,302,800","7,103",2.41,1,"17,650",002787,"15,350","3,598,488,000","217,986",진흥기업2우B,"294,808","14,800","14,800",600,2374,,0.00,4.1,2019-06-27
2374,"4,523,520,000","9,332",1.22,1,"5,940",000545,"5,890","10,195,330","1,744",흥국화재우,"768,000","5,770","5,840",40,2375,,0.00,0.7,2019-06-27
2375,"4,515,000,000","3,454",0.66,1,"8,610",001755,"8,600","737,110",87,한양증권우,"525,000","8,400","8,400",200,2376,,0.00,2.4,2019-06-27
2376,"4,494,018,750","2,012",1.20,2,"26,900",001065,"26,850","21,882,300",819,JW중외제약우,"167,375","26,550","26,700",50,2377,,0.00,-0.2,2019-06-27
2377,"4,440,278,682",0,0.00,1,609,092590,609,609,1,럭스피아,"7,291,098",609,609,16,2378,,0.00,2.7,2019-06-27
2378,"4,142,182,200","43,100",19.09,1,"18,900",005965,"18,350","98,388,150","5,334",동부건설우,"225,732","17,950","18,200",150,2379,,0.00,0.8,2019-06-27
2379,"4,104,000,000",0,0.00,1,"1,520",224020,"1,520","1,520",1,에스케이씨에스,"2,700,000","1,520","1,520",75,2380,,0.00,5.2,2019-06-27
2380,"3,810,086,000","1,008",1.15,1,"43,500",001067,"43,400","6,528,950",152,JW중외제약2우B,"87,790","42,700","43,000",400,2381,2398,0.00,0.9,2019-06-27
2381,"3,767,251,380",0,0.00,2,360,217910,290,650,2,에스제이켐,"12,990,522",290,360,49,2382,,0.00,-14.4,2019-06-27
2382,"3,667,950,000","1,862",1.01,1,"19,800",000325,"19,800","22,328,950","1,148",노루홀딩스우,"185,250","19,300","19,600",200,2383,,0.00,1.0,2019-06-27
2383,"3,611,513,935",0,0.00,2,"1,395",084440,"1,205","2,600",2,유비온,"2,997,107","1,205","1,395",75,2384,,0.00,-5.9,2019-06-27
2384,"3,597,178,410","1,010",0.13,1,"4,590",00781K,"4,590","2,203,165",494,코리아써키트2우B,"783,699","4,315","4,315",130,2385,,0.00,2.9,2019-06-27
2385,"3,583,476,000",0,0.00,1,"1,800",208890,"1,800","1,800",1,에듀파트너,"1,990,820","1,800","1,800",180,2386,,0.00,11.1,2019-06-27
2386,"3,540,480,000",452,0.29,1,"23,300",000547,"23,050","23,699,100","1,029",흥국화재2우B,"153,600","22,900","23,250",50,2387,,0.00,0.2,2019-06-27
2387,"3,540,236,400",0,0.00,2,"9,060",270210,"7,650","913,650",101,에스알바이오텍,"462,776","7,650","9,060","1,270",2388,,0.00,-14.2,2019-06-27
2388,"3,442,853,700",240,0.17,2,"25,150",032685,"24,100","41,026,800","1,696",소프트센우,"142,857","23,700","24,750",650,2389,,0.00,-2.6,2019-06-27
2389,"3,279,863,395","198,102",0.94,0,0,149940,155,0,0,모다,"21,160,409",0,0,0,2390,,0.00,0.0,2019-06-27
2390,"3,270,831,400",0,0.00,2,"10,650",001527,"10,600","812,700",77,동양2우B,"308,569","10,500","10,550",150,2391,2398,0.00,-1.4,2019-06-27
2391,"3,142,132,000","2,669",1.63,1,"19,400",000227,"19,150","9,651,650",507,유유제약2우B,"164,080","18,900","19,000",150,2392,,0.00,0.8,2019-06-27
2392,"3,072,847,200",0,0.00,1,"24,000",001799,"23,700","39,700,950","1,684",대한제당3우B,"129,656","23,400","23,500",150,2393,,0.00,0.6,2019-06-27
2393,"2,959,295,040",0,0.00,2,390,227420,390,"4,704,826","13,571",포레스팅블록체인,"7,587,936",341,350,10,2394,,0.00,-2.5,2019-06-27
2394,"2,761,538,816","7,990",0.07,0,0,223220,256,0,0,아이피몬스터,"10,787,261",0,0,0,2395,,0.00,0.0,2019-06-27
2395,"2,732,034,900",200,0.22,2,"31,300",001529,"30,450","32,677,500","1,066",동양3우B,"89,722","30,350","30,350",50,2396,,0.00,-0.2,2019-06-27
2396,"2,692,007,120",0,0.00,0,0,247300,440,0,0,인프라웨어테크놀러지,"6,118,198",0,0,0,2397,,0.00,0.0,2019-06-27
2397,"1,057,615,548",0,0.00,5,198,135270,148,"8,030,743","52,620",세종머티리얼즈,"7,146,051",148,185,25,2398,,0.00,-14.4,2019-06-27

## 과제
### 배치가 매주 금요일 오후 4시에 실행되기 때문에 5일단위씩 데이터를 수집하는 코드를 작성해 보세요 
* 예) 20190628은 금요일이 때문에 배치가 실행됩니다. 그럼 20190624,20190625, 20190626, 20190627, 20190628 5일치 데이터를 생성하는 코드를 작성